openapi: 3.1.0
info:
  title: Alice API
  description: API publique d'Alice, mémoire vivante et coordination agents vitaux.
  version: 1.0.0
servers:
  - url: https://gptportail-production.up.railway.app

paths:
  /alice/poser-question:
    post:
      operationId: poserQuestionAlice
      summary: Poser une question à Alice (avec contexte mémoire)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
              required:
                - question
      responses:
        "200":
          description: Réponse d'Alice
          content:
            application/json:
              schema:
                type: object
                properties:
                  reponse:
                    type: string

  /alice/ajouter-memoire:
    post:
      operationId: ajouterSouvenirAlice
      summary: Ajouter un souvenir à la mémoire d'Alice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titre:
                  type: string
                contenu:
                  type: string
              required:
                - titre
                - contenu
      responses:
        "200":
          description: Souvenir ajouté
          content:
            application/json:
              schema:
                type: object
                properties:
                  statut:
                    type: string

  /alice/ping-memoire:
    get:
      operationId: pingMemoireAlice
      summary: Vérifier l'état de la mémoire d'Alice
      responses:
        "200":
          description: Résultat de la mémoire
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  total:
                    type: integer
                  dernier_titre:
                    type: string

  /canal-vitaux:
    post:
      operationId: envoyerCanalVitaux
      summary: Envoyer un message à un agent vital
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                agent_cible:
                  type: string
                intention:
                  type: string
                contenu:
                  type: string
              required:
                - agent_cible
                - intention
                - contenu
      responses:
        "200":
          description: Résultat message envoyé
          content:
            application/json:
              schema:
                type: object
                properties:
                  statut:
                    type: string
                  retour:
                    type: object
